import { Injectable } from '@angular/core';
import { Productos } from '../../shared/models/producto';

@Injectable({
  providedIn: 'root'
})
export class ProductoService {

  constructor() { }

  getAll(): Productos[] {
    return [

      //ALFA ROMEO
      {
        id: 1,
        descripcion: 'Camiseta Alfa Romeo F1 2023 Equipo',
        precio: 39,
        escuderia: 'Alfa Romeo',
        imageUrl: '/assets/Productos/AlfaRomeo/Camiseta Alfa Romeo.jpg',
        tags: ['Camiseta', 'Alfa Romeo'],
      },
      {
        id: 2,
        descripcion: 'Chomba Alfa Romeo F1 2023 Equipo',
        precio: 54,
        escuderia: 'Alfa Romeo',
        imageUrl: '/assets/Productos/AlfaRomeo/Chomba-Alfa-Romeo.jpg',
        tags: ['Camiseta', 'Alfa Romeo'],
      },
      {
        id: 3,
        descripcion: 'Buzo Alfa Romeo F1',
        precio: 107,
        escuderia: 'Alfa Romeo',
        imageUrl: '/assets/Productos/AlfaRomeo/BuzoAlfaRomeo.jpg',
        tags: ['Buzo', 'Alfa Romeo'],
      },
      {
        id: 4,
        descripcion: 'Campera Alfa Romeo F1 2023 Equipo',
        precio: 107,
        escuderia: 'Alfa Romeo',
        imageUrl: '/assets/Productos/AlfaRomeo/Campera Alfa Romeo.jpg',
        tags: ['Campera', 'Alfa Romeo'],
      },
      {
        id: 5,
        descripcion: 'Gorra Alfa Romeo Guanyu Zhou',
        precio: 35,
        escuderia: 'Alfa Romeo',
        imageUrl: '/assets/Productos/AlfaRomeo/Gorra Alfa Romeo Guanyu Zhou.jpg',
        tags: ['Gorra', 'Alfa Romeo', 'Guanyu Zhou'],
      },
      {
        id: 6,
        descripcion: 'Gorra Alfa Romeo Valtteri Bottas',
        precio: 35,
        escuderia: 'Alfa Romeo',
        imageUrl: '/assets/Productos/AlfaRomeo/Gorra Alfa Romeo Valterri Bottas.jpg',
        tags: ['Gorra', 'Alfa Romeo', 'Valtteri Bottas'],
      },
      {
        id: 7,
        descripcion: 'Gorra Alfa Romeo Equipo',
        precio: 38,
        escuderia: 'Alfa Romeo',
        imageUrl: '/assets/Productos/AlfaRomeo/Gorra Alfa Romeo.jpg',
        tags: ['Gorra', 'Alfa Romeo'],
      },
      {
        id: 8,
        descripcion: 'Figura Alfa Romeo Guanyu Zhou',
        precio: 84,
        escuderia: 'Alfa Romeo',
        imageUrl: '/assets/Productos/AlfaRomeo/Coche Alfa Romeo Zhou Guanyu.jpg',
        tags: ['Figura', 'Alfa Romeo', 'Guanyu Zhou'],
      },
      {
        id: 9,
        descripcion: 'Figura Alfa Romeo Valtteri Bottas',
        precio: 84,
        escuderia: 'Alfa Romeo',
        imageUrl: '/assets/Productos/AlfaRomeo/Coche Alfa Romeo Valtteri Bottas.jpg',
        tags: ['Figura', 'Alfa Romeo', 'Valtteri Bottas'],
      },

      //ALPHA TAURI
      {
        id: 10,
        descripcion: 'Camiseta Alpha Tauri F1 2023 Equipo',
        precio: 42,
        escuderia: 'Alpha Tauri',
        imageUrl: '/assets/Productos/Alpha Tauri/Camiseta Alpha Tauri.jpg',
        tags: ['Camiseta', 'Alpha Tauri'],
      },
      {
        id: 11,
        descripcion: 'Chomba Alpha Tauri F1 2023 Equipo',
        precio: 73,
        escuderia: 'Alpha Tauri',
        imageUrl: '/assets/Productos/Alpha Tauri/Chomba Alpha Tauri.jpg',
        tags: ['Chomba', 'Alpha Tauri'],
      },
      {
        id: 12,
        descripcion: 'Buzo Alpha Tauri F1 2023 Equipo',
        precio: 58,
        escuderia: 'Alpha Tauri',
        imageUrl: '/assets/Productos/Alpha Tauri/Buzo Alpha Tauri.jpg',
        tags: ['Buzo', 'Alpha Tauri'],
      },
      {
        id: 13,
        descripcion: 'Campera Alpha Tauri F1 2023 Equipo',
        precio: 76,
        escuderia: 'Alpha Tauri',
        imageUrl: '/assets/Productos/Alpha Tauri/Campera Alpha Tauri.jpg',
        tags: ['Campera', 'Alpha Tauri'],
      },
      {
        id: 14,
        descripcion: 'Gorra Alpha Tauri Yuki Tsunoda',
        precio: 39,
        escuderia: 'Alpha Tauri',
        imageUrl: '/assets/Productos/Alpha Tauri/Gorra-Alpha-Tauri-Yuki-Tsunoda.jpg',
        tags: ['Gorra', 'Alpha Tauri', 'Yuki Tsunoda'],
      },
      {
        id: 15,
        descripcion: 'Gorra Alpha Tauri F1 2023 Equipo',
        precio: 24,
        escuderia: 'Alpha Tauri',
        imageUrl: '/assets/Productos/Alpha Tauri/Gorra Alpha Tauri.jpg',
        tags: ['Gorra', 'Alpha Tauri'],
      },
      {
        id: 16,
        descripcion: 'Figura Alpha Tauri Yuki Tsunoda',
        precio: 84,
        escuderia: 'Alpha Tauri',
        imageUrl: '/assets/Productos/Alpha Tauri/Coche Alpha Tauri Yuki Tsunoda.jpg',
        tags: ['Figura', 'Alpha Tauri', 'Yuki Tsunoda'],
      },
      {
        id: 17,
        descripcion: 'Figura Alpha Tauri Nyck de Vries',
        precio: 84,
        escuderia: 'Alpha Tauri',
        imageUrl: '/assets/Productos/Alpha Tauri/Coche Alpha Tauri Nyck de Vries.jpg',
        tags: ['Figura', 'Alpha Tauri', 'Nyck de Vries'],
      },

      //CAMISETA ALPINE
      {
        id: 18,
        descripcion: 'Camiseta Alpine F1 2023 Equipo',
        precio: 39,
        escuderia: 'Alpine',
        imageUrl: '/assets/Productos/Alpine/Camiseta Alpine.jpg',
        tags: ['Camiseta', 'Alpine'],
      },
      {
        id: 19,
        descripcion: 'Chomba Alpine F1 2023 Equipo',
        precio: 59,
        escuderia: 'Alpine',
        imageUrl: '/assets/Productos/Alpine/Chomba Alpine.jpg',
        tags: ['Chomba', 'Alpine'],
      },
      {
        id: 20,
        descripcion: 'Buzo Alpine F1 2023 Equipo',
        precio: 55,
        escuderia: 'Alpine',
        imageUrl: '/assets/Productos/Alpine/Buzo Alpine.jpg',
        tags: ['Buzo', 'Alpine'],
      },
      {
        id: 21,
        descripcion: 'Campera Alpine F1 2023 Equipo',
        precio: 101,
        escuderia: 'Alpine',
        imageUrl: '/assets/Productos/Alpine/Campera Alpine.jpg',
        tags: ['Campera', 'Alpine'],
      },
      {
        id: 22,
        descripcion: 'Gorra Alpine Esteban Ocon',
        precio: 31,
        escuderia: 'Alpine',
        imageUrl: '/assets/Productos/Alpine/Gorra Alpine Esteban Ocon.jpg',
        tags: ['Gorra', 'Alpine', 'Esteban Ocon'],
      },
      {
        id: 23,
        descripcion: 'Gorra Alpine Pierre Gasly',
        precio: 31,
        escuderia: 'Alpine',
        imageUrl: 'assets/Productos/Alpine/Gorra-Alpine-Pierre-Gasly.jpg',
        tags: ['Gorra', 'Alpine', 'Pierre Gasly'],
      },
      {
        id: 24,
        descripcion: 'Gorra Alpine F1 2023 Equipo',
        precio: 42,
        escuderia: 'Alpine',
        imageUrl: '/assets/Productos/Alpine/Gorra Alpine.jpg',
        tags: ['Gorra', 'Alpine'],
      },

      //ASTON MARTIN
      {
        id: 25,
        descripcion: 'Camiseta Aston Martin F1 2023 Equipo',
        precio: 41,
        escuderia: 'Aston Martin',
        imageUrl: '/assets/Productos/Aston Martin/Camiseta Aston Martin.jpg',
        tags: ['Camiseta', 'Aston Martin'],
      },
      {
        id: 26,
        descripcion: 'Chomba Aston Martin F1 2023 Equipo',
        precio: 53,
        escuderia: 'Aston Martin',
        imageUrl: '/assets/Productos/Aston Martin/Chomba-Aston-Martin.jpg',
        tags: ['Chomba', 'Aston Martin'],
      },
      {
        id: 27,
        descripcion: 'Buzo Aston Martin F1 2023 Equipo',
        precio: 82,
        escuderia: 'Aston Martin',
        imageUrl: '/assets/Productos/Aston Martin/Buzo Aston Martin.jpg',
        tags: ['Buzo', 'Aston Martin'],
      },
      {
        id: 28,
        descripcion: 'Campera Aston Martin F1 2023 Equipo',
        precio: 186,
        escuderia: 'Aston Martin',
        imageUrl: '/assets/Productos/Aston Martin/Campera Aston Martin.jpg',
        tags: ['Campera', 'Aston Martin'],
      },
      {
        id: 29,
        descripcion: 'Gorra Aston Martin Fernando Alonso',
        precio: 27,
        escuderia: 'Aston Martin',
        imageUrl: 'assets/Productos/Aston Martin/Gorra-Aston-Martin-Fernando-Alonso.jpg',
        tags: ['Gorra', 'Aston Martin', 'Fernando Alonso'],
      },
      {
        id: 30,
        descripcion: 'Gorra Aston Martin Lance Stroll',
        precio: 27,
        escuderia: 'Aston Martin',
        imageUrl: 'assets/Productos/Aston Martin/Gorra-Aston-Martin-Lance-Stroll.jpg',
        tags: ['Gorra', 'Aston Martin', 'Lance Stroll'],
      },
      {
        id: 31,
        descripcion: 'Gorra Aston Martin F1 2023 Equipo',
        precio: 27,
        escuderia: 'Aston Martin',
        imageUrl: '/assets/Productos/Aston Martin/Gorra Aston Martin.jpg',
        tags: ['Gorra', 'Aston Martin'],
      },

      //FERRARI
      {
        id: 32,
        descripcion: 'Camiseta Ferrari F1 2023 Equipo',
        precio: 47,
        escuderia: 'Ferrari',
        imageUrl: '/assets/Productos/Ferrari/Camiseta Ferrari.jpg',
        tags: ['Camiseta', 'Ferrari'],
      },
      {
        id: 33,
        descripcion: 'Chomba Ferrari F1 2023 Equipo',
        precio: 58,
        escuderia: 'Ferrari',
        imageUrl: '/assets/Productos/Ferrari/Chomba Ferrari.jpg',
        tags: ['Chomba', 'Ferrari'],
      },
      {
        id: 34,
        descripcion: 'Buzo Ferrari F1 2023 Equipo',
        precio: 96,
        escuderia: 'Ferrari',
        imageUrl: '/assets/Productos/Ferrari/Buzo Ferrari.jpg',
        tags: ['Buzo', 'Ferrari'],
      },
      {
        id: 35,
        descripcion: 'Campera Ferrari F1 2023 Equipo',
        precio: 116,
        escuderia: 'Ferrari',
        imageUrl: '/assets/Productos/Ferrari/Campera Ferrari.jpg',
        tags: ['Campera', 'Ferrari'],
      },
      {
        id: 36,
        descripcion: 'Gorra Ferrari Charles Leclerc',
        precio: 42,
        escuderia: 'Ferrari',
        imageUrl: 'assets/Productos/Ferrari/Gorra-Ferrari-Charles-Leclerc.jpg',
        tags: ['Gorra', 'Ferrari', 'Charles Leclerc'],
      },
      {
        id: 37,
        descripcion: 'Gorra Ferrari Carlos Sainz',
        precio: 42,
        escuderia: 'Ferrari',
        imageUrl: 'assets/Productos/Ferrari/Gorra-Ferrari-Carlos-Sainz.jpg',
        tags: ['Gorra', 'Ferrari', 'Carlos Sainz'],
      },
      {
        id: 38,
        descripcion: 'Gorra Ferrari F1 2023 Equipo',
        precio: 38,
        escuderia: 'Ferrari',
        imageUrl: '/assets/Productos/Ferrari/Gorra Ferrari.jpg',
        tags: ['Gorra', 'Ferrari'],
      },
      {
        id: 39,
        descripcion: 'Figura Ferrari Charles Leclerc',
        precio: 56,
        escuderia: 'Ferrari',
        imageUrl: '/assets/Productos/Ferrari/Coche Ferrari Charles Leclerc.jpg',
        tags: ['Figura', 'Ferrari', 'Charles Leclerc'],
      },
      {
        id: 50,
        descripcion: 'Figura Ferrari Carlos Sainz',
        precio: 56,
        escuderia: 'Ferrari',
        imageUrl: '/assets/Productos/Ferrari/Coche Ferrari Carlos Sainz.jpg',
        tags: ['Figura', 'Ferrari', 'Carlos Sainz'],
      },

      //MCLAREN
      {
        id: 51,
        descripcion: 'Camiseta McLaren F1 2023 Equipo',
        precio: 51,
        escuderia: 'McLaren',
        imageUrl: '/assets/Productos/McLaren/Camiseta McLaren.jpg',
        tags: ['Camiseta', 'McLaren'],
      },
      {
        id: 52,
        descripcion: 'Chomba McLaren F1 2023 Equipo',
        precio: 66,
        escuderia: 'McLaren',
        imageUrl: '/assets/Productos/McLaren/Chomba McLaren.jpg',
        tags: ['Chomba', 'McLaren'],
      },
      {
        id: 53,
        descripcion: 'Buzo McLaren F1 2023 Equipo',
        precio: 86,
        escuderia: 'McLaren',
        imageUrl: '/assets/Productos/McLaren/Buzo McLaren.jpg',
        tags: ['Buzo', 'McLaren'],
      },
      {
        id: 54,
        descripcion: 'Campera McLaren F1 2023 Equipo',
        precio: 121,
        escuderia: 'McLaren',
        imageUrl: '/assets/Productos/McLaren/Campera McLaren.jpg',
        tags: ['Campera', 'McLaren'],
      },
      {
        id: 55,
        descripcion: 'Gorra McLaren Lando Norris',
        precio: 45,
        escuderia: 'McLaren',
        imageUrl: 'assets/Productos/McLaren/Gorra-McLaren-Lando-Norris.jpg',
        tags: ['Gorra', 'McLaren', 'Lando Norris'],
      },
      {
        id: 56,
        descripcion: 'Gorra McLaren Oscar Piastri',
        precio: 45,
        escuderia: 'McLaren',
        imageUrl: 'assets/Productos/McLaren/Gorra-McLaren-Oscar-Piastri.jpg',
        tags: ['Gorra', 'McLaren', 'Oscar Piastri'],
      },
      {
        id: 57,
        descripcion: 'Gorra McLaren F1 2023 Equipo',
        precio: 45,
        escuderia: 'McLaren',
        imageUrl: '/assets/Productos/McLaren/Gorra McLaren.jpg',
        tags: ['Gorra', 'McLaren'],
      },
      {
        id: 58,
        descripcion: 'Figura McLaren Lando Norris',
        precio: 54,
        escuderia: 'McLaren',
        imageUrl: '/assets/Productos/McLaren/Coche McLaren Lando Norris.jpg',
        tags: ['Figura', 'McLaren', 'Lando Norris'],
      },

      //MERCEDES AMG
      {
        id: 59,
        descripcion: 'Camiseta Mercedes AMG F1 2023 Equipo',
        precio: 44,
        escuderia: 'Mercedes AMG',
        imageUrl: '/assets/Productos/Mercedes AMG/Camiseta Mercedes AMG.jpg',
        tags: ['Camiseta', 'Mercedes AMG'],
      },
      {
        id: 60,
        descripcion: 'Chomba Mercedes AMG F1 2023 Equipo',
        precio: 54,
        escuderia: 'Mercedes AMG',
        imageUrl: '/assets/Productos/Mercedes AMG/Chomba Mercedes AMG.jpg',
        tags: ['Chomba', 'Mercedes AMG'],
      },
      {
        id: 61,
        descripcion: 'Buzo Mercedes AMG F1 2023 Equipo',
        precio: 86,
        escuderia: 'Mercedes AMG',
        imageUrl: '/assets/Productos/Mercedes AMG/Buzo Mercedes AMG.jpg',
        tags: ['Buzo', 'Mercedes AMG'],
      },
      {
        id: 62,
        descripcion: 'Campera Mercedes AMG F1 2023 Equipo',
        precio: 119,
        escuderia: 'Mercedes AMG',
        imageUrl: '/assets/Productos/Mercedes AMG/Campera Mercedes AMG.jpg',
        tags: ['Campera', 'Mercedes AMG'],
      },
      {
        id: 63,
        descripcion: 'Gorra Mercedes AMG Lewis Hamilton',
        precio: 34,
        escuderia: 'Mercedes AMG',
        imageUrl: 'assets/Productos/Mercedes AMG/Gorra Mercedes Lewis Hamilton.jpg',
        tags: ['Gorra', 'Mercedes AMG', 'Lewis Hamilton'],
      },
      {
        id: 64,
        descripcion: 'Gorra Mercedes AMG George Russell',
        precio: 34,
        escuderia: 'Mercedes AMG',
        imageUrl: 'assets/Productos/Mercedes AMG/Gorra Mercedes George Russell.jpg',
        tags: ['Gorra', 'Mercedes AMG', 'George Russell'],
      },
      {
        id: 65,
        descripcion: 'Gorra Mercedes AMG F1 2023 Equipo',
        precio: 30,
        escuderia: 'Mercedes AMG',
        imageUrl: '/assets/Productos/Mercedes AMG/Gorra Mercedes AMG.jpg',
        tags: ['Gorra', 'Mercedes AMG'],
      },
      {
        id: 66,
        descripcion: 'Figura Mercedes AMG Lewis Hamilton',
        precio: 84,
        escuderia: 'Mercedes AMG',
        imageUrl: '/assets/Productos/Mercedes AMG/Coche Mercedes AMG Lewis Hamilton.jpg',
        tags: ['Figura', 'Mercedes AMG', 'Lewis Hamilton'],
      },
      {
        id: 67,
        descripcion: 'Figura Mercedes AMG George Russell',
        precio: 84,
        escuderia: 'Mercedes AMG',
        imageUrl: '/assets/Productos/Mercedes AMG/Coche Mercedes AMG George Russell.jpg',
        tags: ['Figura', 'Mercedes AMG', 'George Russell'],
      },

      //RED BULL
      {
        id: 68,
        descripcion: 'Camiseta Red Bull F1 2023 Equipo',
        precio: 42,
        escuderia: 'Red Bull',
        imageUrl: '/assets/Productos/Red Bull/Camiseta Red Bull.jpg',
        tags: ['Camiseta', 'Red Bull'],
      },
      {
        id: 69,
        descripcion: 'Chomba Red Bull F1 2023 Equipo',
        precio: 63,
        escuderia: 'Red Bull',
        imageUrl: '/assets/Productos/Red Bull/Chomba Red Bull.jpg',
        tags: ['Chomba', 'Red Bull'],
      },
      {
        id: 70,
        descripcion: 'Buzo Red Bull F1 2023 Equipo',
        precio: 76,
        escuderia: 'Red Bull',
        imageUrl: '/assets/Productos/Red Bull/Buzo Red Bull.jpg',
        tags: ['Buzo', 'Red Bull'],
      },
      {
        id: 71,
        descripcion: 'Campera Red Bull F1 2023 Equipo',
        precio: 135,
        escuderia: 'Red Bull',
        imageUrl: '/assets/Productos/Red Bull/Campera Red Bull.jpg',
        tags: ['Campera', 'Red Bull'],
      },
      {
        id: 72,
        descripcion: 'Gorra Red Bull Max Verstappen',
        precio: 30,
        escuderia: 'Red Bull',
        imageUrl: 'assets/Productos/Red Bull/Gorra Red Bull Max Verstappen.jpg',
        tags: ['Gorra', 'Red Bull', 'Max Verstappen'],
      },
      {
        id: 73,
        descripcion: 'Gorra Red Bull Sergio Pérez',
        precio: 30,
        escuderia: 'Red Bull',
        imageUrl: 'assets/Productos/Red Bull/Gorra Red Bull Sergio Pérez.jpg',
        tags: ['Gorra', 'Red Bull', 'Sergio Pérez'],
      },
      {
        id: 74,
        descripcion: 'Gorra Red Bull F1 2023 Equipo',
        precio: 36,
        escuderia: 'Red Bull',
        imageUrl: '/assets/Productos/Red Bull/Gorra-Red-Bull.jpg',
        tags: ['Gorra', 'Red Bull'],
      },
      {
        id: 75,
        descripcion: 'Figura Red Bull Max Verstappen',
        precio: 84,
        escuderia: 'Red Bull',
        imageUrl: '/assets/Productos/Red Bull/Coche Red Bull Max Verstappen.jpg',
        tags: ['Figura', 'Red Bull', 'Max Verstappen'],
      },
      {
        id: 76,
        descripcion: 'Figura Red Bull Sergio Pérez',
        precio: 84,
        escuderia: 'Red Bull',
        imageUrl: '/assets/Productos/Red Bull/Coche-Red-Bull-Sergio-Perez.jpg',
        tags: ['Figura', 'Red Bull', 'Sergio Pérez'],
      },

      //WILLIAMS
      {
        id: 77,
        descripcion: 'Camiseta Williams F1 2023 Equipo',
        precio: 56,
        escuderia: 'Williams',
        imageUrl: '/assets/Productos/Williams/Camiseta Williams.jpg',
        tags: ['Camiseta', 'Williams'],
      },
      {
        id: 78,
        descripcion: 'Chomba Williams F1 2023 Equipo',
        precio: 43,
        escuderia: 'Williams',
        imageUrl: '/assets/Productos/Williams/Chomba Williams.jpg',
        tags: ['Chomba', 'Williams'],
      },
      {
        id: 79,
        descripcion: 'Buzo Williams F1 2023 Equipo',
        precio: 47,
        escuderia: 'Williams',
        imageUrl: '/assets/Productos/Williams/Buzo Williams.jpg',
        tags: ['Buzo', 'Williams'],
      },
      {
        id: 80,
        descripcion: 'Campera Williams F1 2023 Equipo',
        precio: 55,
        escuderia: 'Williams',
        imageUrl: '/assets/Productos/Williams/Campera Williams.jpg',
        tags: ['Campera', 'Williams'],
      },
      {
        id: 81,
        descripcion: 'Campera Williams F1 2023 Equipo',
        precio: 55,
        escuderia: 'Williams',
        imageUrl: '/assets/Productos/Williams/Campera Williams.jpg',
        tags: ['Campera', 'Williams'],
      },
    ];
  }
}
